sudo: false

language: node_js
os:
  - linux # turned off until we can figure out why it is only failing on linux
  - osx
node_js:
  - "node"
  - "12"
  - "10"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - npm test
  # - npm run test-client-integration
