name: " ðŸ¤– Update Dependabot ðŸ¤–"

on:
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: "main"

  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read

jobs:
  update-dependabot:
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: update-dependabot-${{ inputs.base || 'main' }}
      REF_BRANCH: ${{ inputs.base || 'main' }}
      PR_TYPE: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 20.x
          cache: "pnpm"

      - name: Run Action
        id: dependabot
        uses: streetsidesoftware/actions/public/update-dependabot-github-actions@v1
        with:
          prefix: chore

      - name: Echo Result
        env:
          SUMMARY: ${{ steps.dependabot.outputs.summary }}
        run: |
          echo "$SUMMARY"

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: "${{ env.PR_TYPE }}: Workflow Bot -- Update dependabot.yml"
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: "${{ env.PR_TYPE }}: Workflow Bot -- Update dependabot.yml (${{ env.REF_BRANCH }})"
          body: ${{ steps.dependabot.outputs.summary }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
